name: Markets CI

env:
  NODE_VERSION: 18
  is-main-branch: ${{ github.ref == 'refs/heads/main' }}
  is-pull-request: ${{ github.event_name == 'pull_request' }}

on:
  pull_request: {}
  workflow_dispatch: {}
  push:
    branches:
      - main

jobs:
  main:
    name: Markets CI Pipe
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          # We need to fetch all branches and commits so that Nx affected has a base to compare against.
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm

      - name: Derive NX Affected SHAs
        id: setSHAs
        uses: nrwl/nx-set-sha@3

      - run: |
          echo 'BASE ${{ steps.setSHAs.outputs.base }}'
          echo 'HEAD ${{ steps.setSHAs.outputs.base }}'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: nx affected --target=build --parallel=3

      - name: Test
        run: nx affected --target=test --parallel=3

      - name: Lint
        run: npx nx affected --target=lint --parallel=3

  deploy:
    name: Deploy
    needs: main
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Install dependencies
        run: npm ci

      - name: Build Dev
        run: npm run build:prod

      - name: Deploy Dev
        if: ${{ env.is-pull-request == 'true' }}
        run: npm run deploy:dev

      - name: Deploy Prod
        if: ${{ env.is-main-branch == 'true' }}
        run: npm run deploy:prod

  user-flows:
    name: User Flows
    needs: main
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run User Flows
        run: npm run user-flows

      - name: Archive User Flow Reports
        uses: actions/upload-artifact@v3
        with:
          name: user-flows-reports
          path: apps/maritime-user-flows/src/measures/
          retention-days: 5
